
'use strict';
const $=id=>document.getElementById(id), NS='http://www.w3.org/2000/svg';
const stage=$('stage'), workCanvas=$('workCanvas'), wctx=workCanvas.getContext('2d',{willReadFrequently:true}), photoCanvas=$('photoCanvas'), pctx=photoCanvas.getContext('2d'), loupeCanvas=$('loupeCanvas'), lctx=loupeCanvas.getContext('2d');
let graph={nodes:[],links:[]}, selected=null, history=[], future=[], view={x:0,y:0,w:1200,h:800};
let imageDataUrl='', photoImg=new Image(), sourceWidth=0, sourceHeight=0, sourceMP=0, rotation=0, contrastOn=false, activeTool='select', linkStart=null, traceStartId=null, tracePoints=[], tracing=false, photoPointer=null;
let snapData=null,snapW=0,snapH=0, training={color:null,count:0}, lastAnalysis={w:0,h:0}, photoCam={z:1,x:0,y:0};
function uid(p){return p+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7)}
function clone(v){return JSON.parse(JSON.stringify(v))}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function snapshot(){history.push(clone(graph));if(history.length>60)history.shift();future=[];updateUI()}
function restore(g){graph=clone(g);selected=null;linkStart=null;renderAll()}
function undo(){if(!history.length)return;future.push(clone(graph));restore(history.pop())}
function redo(){if(!future.length)return;history.push(clone(graph));restore(future.pop())}
function setStatus(t,kind=''){const e=$('status');e.textContent=t;e.className='status'+(kind?' '+kind:'')}
function setTool(t){activeTool=t;linkStart=null;traceStartId=t==='trace'?traceStartId:null;document.querySelectorAll('.toolBtn').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));const hints={select:'Sélectionnez un élément.',trace:'Tracez une branche sur la photo.',link:'Choisissez le départ puis l’arrivée.',cut:'Touchez une relation pour la supprimer.',add:'Touchez la photo ou la carte pour créer un nœud.'};$('toolHint').textContent=hints[t]||'';$('photoTipText').textContent=hints[t]||'';drawPhoto()}
function svgEl(n,a={}){const e=document.createElementNS(NS,n);for(const[k,v]of Object.entries(a))e.setAttribute(k,v);return e}
function wrapLabel(s,max=24){const words=String(s||'Sans titre').split(/\s+/),out=[];let line='';for(const w of words){const n=(line+' '+w).trim();if(n.length>max&&line){out.push(line);line=w}else line=n}if(line)out.push(line);return out.length?out:['Sans titre']}
function nodeSize(n){const lines=wrapLabel(n.label);return{w:Math.max(120,Math.min(270,Math.max(...lines.map(x=>x.length))*7.7+34)),h:Math.max(48,lines.length*18+24),lines}}
function edgePoints(a,b){const A=nodeSize(a),B=nodeSize(b),dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1,ux=dx/d,uy=dy/d;const ra=Math.min(Math.abs((A.w/2)/(ux||.0001)),Math.abs((A.h/2)/(uy||.0001))),rb=Math.min(Math.abs((B.w/2)/(ux||.0001)),Math.abs((B.h/2)/(uy||.0001)));return{x1:a.x+ux*Math.min(ra,d/3),y1:a.y+uy*Math.min(ra,d/3),x2:b.x-ux*Math.min(rb,d/3),y2:b.y-uy*Math.min(rb,d/3)}}
function updateUI(){const nn=graph.nodes.length,ne=graph.links.length;$('countBadge').textContent=`${nn} nœud${nn>1?'s':''} · ${ne} relation${ne>1?'s':''}`;$('undoBtn').disabled=!history.length;$('redoBtn').disabled=!future.length;const insp=$('inspector');if(!selected){insp.classList.remove('on');$('selectionInfo').textContent='aucune sélection';return}insp.classList.add('on');const n=selected.kind==='node'?graph.nodes.find(x=>x.id===selected.id):null,e=selected.kind==='edge'?graph.links.find(x=>x.id===selected.id):null;$('nodeFields').style.display=n?'block':'none';$('edgeFields').style.display=e?'block':'none';$('continueBtn').disabled=!n&&!e;if(n){$('inspectorTitle').textContent=n.verified?'Nœud vérifié':'Nœud';$('selectionInfo').textContent=n.label;$('labelInput').value=n.label||'';$('nodeType').value=n.type||'concept';if(n.crop){$('cropPreview').src=n.crop;$('cropPreview').style.display='block'}else $('cropPreview').style.display='none'}if(e){$('inspectorTitle').textContent=e.verified?'Relation vérifiée':'Relation';$('selectionInfo').textContent=e.label||'relation';$('edgeLabel').value=e.label||'';$('edgeType').value=e.type||'causal'}}
function renderMap(){stage.innerHTML='';stage.setAttribute('viewBox',`${view.x} ${view.y} ${view.w} ${view.h}`);const defs=svgEl('defs'),marker=svgEl('marker',{id:'arrow',viewBox:'0 0 10 10',refX:'9',refY:'5',markerWidth:'7',markerHeight:'7',orient:'auto-start-reverse'});marker.append(svgEl('path',{d:'M 0 0 L 10 5 L 0 10 z',fill:'#64748b'}));defs.append(marker);stage.append(defs);const byId=Object.fromEntries(graph.nodes.map(n=>[n.id,n]));for(const l of graph.links){const a=byId[l.from],b=byId[l.to];if(!a||!b)continue;const p=edgePoints(a,b),g=svgEl('g',{class:`edge ${l.type||'causal'} ${selected?.kind==='edge'&&selected.id===l.id?'selected':''} ${l.verified?'verified':''}`});const path=svgEl('path',{d:`M ${p.x1} ${p.y1} L ${p.x2} ${p.y2}`,'marker-end':'url(#arrow)'});g.append(path);if(l.label){const t=svgEl('text',{x:(p.x1+p.x2)/2,y:(p.y1+p.y2)/2-8,'text-anchor':'middle'});t.textContent=l.label;g.append(t)}g.addEventListener('pointerdown',ev=>{ev.stopPropagation();if(activeTool==='cut'){snapshot();graph.links=graph.links.filter(x=>x.id!==l.id);selected=null;renderAll();return}selected={kind:'edge',id:l.id};renderAll()});stage.append(g)}for(const n of graph.nodes){const s=nodeSize(n),g=svgEl('g',{class:`node ${selected?.kind==='node'&&selected.id===n.id?'selected':''} ${n.verified?'verified':''}`,transform:`translate(${n.x},${n.y})`});g.append(svgEl('rect',{x:-s.w/2,y:-s.h/2,width:s.w,height:s.h,rx:14}));s.lines.forEach((line,i)=>{const t=svgEl('text',{'text-anchor':'middle',x:0,y:(i-(s.lines.length-1)/2)*18+5});t.textContent=line;g.append(t)});g.addEventListener('pointerdown',ev=>nodePointerDown(ev,n,g));g.addEventListener('dblclick',ev=>{ev.stopPropagation();selected={kind:'node',id:n.id};renderAll();setTimeout(()=>$('labelInput').focus(),0)});stage.append(g)}updateUI()}
function svgPoint(e){const pt=stage.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;return pt.matrixTransform(stage.getScreenCTM().inverse())}
function linkNode(id){if(!linkStart){linkStart=id;selected={kind:'node',id};setStatus('Départ choisi. Touchez le nœud d’arrivée.');renderAll();return}if(linkStart===id)return;snapshot();graph.links.push({id:uid('e'),from:linkStart,to:id,label:'',type:'influence',confidence:1,verified:true});linkStart=null;selected=null;setTool('select');setStatus('Relation créée.','ok');renderAll()}
function nodePointerDown(e,n,g){e.stopPropagation();if(activeTool==='link'){linkNode(n.id);return}if(activeTool==='cut')return;if(activeTool==='trace'){selected={kind:'node',id:n.id};traceStartId=n.id;setStatus('Départ de branche fixé. Tracez maintenant sur la photo.');renderAll();return}selected={kind:'node',id:n.id};updateUI();if(activeTool!=='select')return;const st=svgPoint(e),ox=n.x-st.x,oy=n.y-st.y,orig={x:n.x,y:n.y};g.setPointerCapture(e.pointerId);const mv=ev=>{const p=svgPoint(ev);n.x=p.x+ox;n.y=p.y+oy;renderMap()};const up=()=>{g.removeEventListener('pointermove',mv);g.removeEventListener('pointerup',up);if(Math.hypot(n.x-orig.x,n.y-orig.y)>2){history.push({...clone(graph),nodes:graph.nodes.map(x=>x.id===n.id?{...x,x:orig.x,y:orig.y}:x)});future=[]}renderAll()};g.addEventListener('pointermove',mv);g.addEventListener('pointerup',up)}
function addMapNodeAt(x,y,source=null){snapshot();const n={id:uid('n'),label:'Nouveau nœud',x,y,type:'concept',confidence:100,verified:true};if(source)n.source=source;graph.nodes.push(n);selected={kind:'node',id:n.id};renderAll();setTimeout(()=>$('labelInput').focus(),0);return n}
let panning=false,panStart=null,viewStart=null;stage.addEventListener('pointerdown',e=>{if(e.target!==stage)return;if(activeTool==='add'){const p=svgPoint(e);addMapNodeAt(p.x,p.y);return}selected=null;updateUI();if(activeTool!=='select')return;panning=true;panStart={x:e.clientX,y:e.clientY};viewStart={...view};stage.setPointerCapture(e.pointerId)});stage.addEventListener('pointermove',e=>{if(!panning)return;const r=stage.getBoundingClientRect(),dx=(e.clientX-panStart.x)*view.w/r.width,dy=(e.clientY-panStart.y)*view.h/r.height;view.x=viewStart.x-dx;view.y=viewStart.y-dy;stage.setAttribute('viewBox',`${view.x} ${view.y} ${view.w} ${view.h}`)});stage.addEventListener('pointerup',()=>panning=false);stage.addEventListener('wheel',e=>{e.preventDefault();zoomMap(e.deltaY>0?1.1:.9)},{passive:false});
function zoomMap(f){const cx=view.x+view.w/2,cy=view.y+view.h/2;view.w=clamp(view.w*f,220,5000);view.h=view.w*2/3;view.x=cx-view.w/2;view.y=cy-view.h/2;renderMap()}
function fitMap(){if(!graph.nodes.length){view={x:0,y:0,w:1200,h:800};renderMap();return}const xs=graph.nodes.map(n=>n.x),ys=graph.nodes.map(n=>n.y),minX=Math.min(...xs)-180,maxX=Math.max(...xs)+180,minY=Math.min(...ys)-120,maxY=Math.max(...ys)+120;view={x:minX,y:minY,w:Math.max(450,maxX-minX),h:Math.max(300,maxY-minY)};const ratio=stage.clientWidth/Math.max(1,stage.clientHeight),vr=view.w/view.h;if(vr>ratio){const h=view.w/ratio;view.y-=(h-view.h)/2;view.h=h}else{const w=view.h*ratio;view.x-=(w-view.w)/2;view.w=w}renderMap()}
function autoLayout(){if(!graph.nodes.length)return;snapshot();const incoming=new Map(graph.nodes.map(n=>[n.id,0]));graph.links.forEach(e=>incoming.set(e.to,(incoming.get(e.to)||0)+1));const root=graph.nodes.find(n=>incoming.get(n.id)===0)||graph.nodes[0],children=new Map(graph.nodes.map(n=>[n.id,[]]));graph.links.forEach(e=>children.get(e.from)?.push(e.to));const levels=new Map([[root.id,0]]),q=[root.id];while(q.length){const id=q.shift(),lv=levels.get(id);for(const c of children.get(id)||[])if(!levels.has(c)){levels.set(c,lv+1);q.push(c)}}const maxL=Math.max(0,...levels.values());for(let lv=0;lv<=maxL;lv++){const arr=graph.nodes.filter(n=>(levels.get(n.id)??maxL+1)===lv);arr.forEach((n,i)=>{n.x=170+lv*270;n.y=110+(i+1)*650/(arr.length+1)})}const rest=graph.nodes.filter(n=>!levels.has(n.id));rest.forEach((n,i)=>{n.x=170+(maxL+1)*270;n.y=110+(i+1)*650/(rest.length+1)});renderAll();fitMap()}
function displayDims(){return rotation%180===0?{w:sourceWidth,h:sourceHeight}:{w:sourceHeight,h:sourceWidth}}
function photoRect(){const r=photoCanvas.getBoundingClientRect(),d=displayDims();if(!d.w||!d.h)return{x:0,y:0,w:r.width,h:r.height,scale:1};const s=Math.min(r.width/d.w,r.height/d.h)*photoCam.z,w=d.w*s,h=d.h*s;return{x:(r.width-w)/2+photoCam.x,y:(r.height-h)/2+photoCam.y,w,h,scale:s}}
function resetPhotoCam(){photoCam={z:1,x:0,y:0};drawPhoto()}
function zoomPhotoAt(factor,cx,cy){const before=photoRect();photoCam.z=clamp(photoCam.z*factor,.4,12);const after=photoRect();if(cx!=null){photoCam.x+=cx-after.x-(cx-before.x)*after.w/before.w;photoCam.y+=cy-after.y-(cy-before.y)*after.h/before.h}drawPhoto()}
function normToPhoto(n){const r=photoRect();return{x:r.x+n.x*r.w,y:r.y+n.y*r.h}}
function photoToNorm(clientX,clientY){const b=photoCanvas.getBoundingClientRect(),r=photoRect(),x=clientX-b.left,y=clientY-b.top;return{x:clamp((x-r.x)/r.w,0,1),y:clamp((y-r.y)/r.h,0,1),inside:x>=r.x&&x<=r.x+r.w&&y>=r.y&&y<=r.y+r.h}}
function orientedToOriginal(n){const u=n.x,v=n.y,rot=((rotation%360)+360)%360;if(rot===90)return{x:v,y:1-u};if(rot===180)return{x:1-u,y:1-v};if(rot===270)return{x:1-v,y:u};return{x:u,y:v}}
function resizePhotoCanvas(){const b=$('photoStage').getBoundingClientRect(),dpr=Math.min(3,window.devicePixelRatio||1),w=Math.max(1,Math.round(b.width*dpr)),h=Math.max(1,Math.round(b.height*dpr));if(photoCanvas.width!==w||photoCanvas.height!==h){photoCanvas.width=w;photoCanvas.height=h;pctx.setTransform(dpr,0,0,dpr,0,0)}pctx.imageSmoothingEnabled=photoCam.z<2.4;pctx.imageSmoothingQuality='high';drawPhoto()}
function drawImageOriented(ctx,rect){if(!photoImg.naturalWidth)return;ctx.save();ctx.translate(rect.x+rect.w/2,rect.y+rect.h/2);ctx.rotate(rotation*Math.PI/180);ctx.filter=contrastOn?'contrast(170%) grayscale(100%)':'none';const sw=rotation%180===0?rect.w:rect.h,sh=rotation%180===0?rect.h:rect.w;ctx.drawImage(photoImg,-sw/2,-sh/2,sw,sh);ctx.restore()}
function drawPhoto(){const b=photoCanvas.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1);pctx.setTransform(dpr,0,0,dpr,0,0);pctx.clearRect(0,0,b.width,b.height);pctx.fillStyle='#e2e8f0';pctx.fillRect(0,0,b.width,b.height);if(!photoImg.naturalWidth)return;const r=photoRect();drawImageOriented(pctx,r);pctx.save();pctx.lineCap='round';pctx.lineJoin='round';for(const e of graph.links){const pts=(e.sourcePath&&e.sourcePath.length?e.sourcePath:null)||(()=>{const a=graph.nodes.find(n=>n.id===e.from)?.source,bn=graph.nodes.find(n=>n.id===e.to)?.source;return a&&bn?[{x:a.x,y:a.y},{x:bn.x,y:bn.y}]:null})();if(!pts)continue;pctx.beginPath();pts.forEach((n,i)=>{const p=normToPhoto(n);i?pctx.lineTo(p.x,p.y):pctx.moveTo(p.x,p.y)});pctx.strokeStyle=selected?.kind==='edge'&&selected.id===e.id?'rgba(15,23,42,.95)':e.verified?'rgba(22,101,52,.88)':'rgba(2,132,199,.72)';pctx.lineWidth=selected?.kind==='edge'&&selected.id===e.id?5:3;pctx.stroke()}for(const n of graph.nodes){if(!n.source)continue;const p=normToPhoto(n.source),sel=selected?.kind==='node'&&selected.id===n.id;pctx.beginPath();pctx.arc(p.x,p.y,sel?10:7,0,Math.PI*2);pctx.fillStyle=sel?'#0f172a':n.verified?'#166534':'#f59e0b';pctx.fill();pctx.strokeStyle='#fff';pctx.lineWidth=2;pctx.stroke();if(sel){pctx.font='600 12px system-ui';pctx.fillStyle='#0f172a';pctx.fillText(n.label||'Nœud',p.x+12,p.y-10)}}if(tracePoints.length){pctx.beginPath();tracePoints.forEach((n,i)=>{const p=normToPhoto(n);i?pctx.lineTo(p.x,p.y):pctx.moveTo(p.x,p.y)});pctx.strokeStyle='#0f172a';pctx.lineWidth=4;pctx.setLineDash([7,5]);pctx.stroke();pctx.setLineDash([])}pctx.restore()}
function drawLoupe(n){if(!photoImg.naturalWidth)return;const orig=orientedToOriginal(n),W=photoImg.naturalWidth,H=photoImg.naturalHeight,size=Math.max(120,Math.min(W,H)*.045),sx=clamp(orig.x*W-size/2,0,Math.max(0,W-size)),sy=clamp(orig.y*H-size/2,0,Math.max(0,H-size));lctx.clearRect(0,0,220,220);lctx.save();lctx.translate(110,110);lctx.rotate(rotation*Math.PI/180);lctx.drawImage(photoImg,sx,sy,size,size,-110,-110,220,220);lctx.restore();lctx.strokeStyle='rgba(15,23,42,.85)';lctx.lineWidth=1;lctx.beginPath();lctx.moveTo(90,110);lctx.lineTo(130,110);lctx.moveTo(110,90);lctx.lineTo(110,130);lctx.stroke();$('loupe').classList.add('on')}
function distPointSegment(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;if(!l)return Math.hypot(p.x-a.x,p.y-a.y);const t=clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/l,0,1),x=a.x+t*dx,y=a.y+t*dy;return Math.hypot(p.x-x,p.y-y)}
function nearestNodeAt(n,max=.04){let best=null,bd=max;for(const node of graph.nodes){if(!node.source)continue;const d=Math.hypot(n.x-node.source.x,n.y-node.source.y);if(d<bd){bd=d;best=node}}return best}
function nearestEdgeAt(n,max=.028){let best=null,bd=max;for(const e of graph.links){const pts=e.sourcePath?.length?e.sourcePath:null;if(!pts)continue;for(let i=1;i<pts.length;i++){const d=distPointSegment(n,pts[i-1],pts[i]);if(d<bd){bd=d;best=e}}}return best}
function selectFromPhoto(n){const node=nearestNodeAt(n,.045);if(node){selected={kind:'node',id:node.id};renderAll();return}const edge=nearestEdgeAt(n,.03);selected=edge?{kind:'edge',id:edge.id}:null;renderAll()}
function photoMapPosition(n){return{x:110+n.x*980,y:80+n.y*640}}
function makePhotoNode(n,label='Nouveau nœud'){const p=photoMapPosition(n),node={id:uid('n'),label,x:p.x,y:p.y,type:'concept',source:{x:n.x,y:n.y},confidence:100,verified:true};graph.nodes.push(node);return node}
async function ensureSnapCanvas(){if(!photoImg.naturalWidth)return;const max=Math.max(chosenMaxDimension('organic'),8192),scale=Math.min(1,max/Math.max(photoImg.naturalWidth,photoImg.naturalHeight)),rw=Math.round(photoImg.naturalWidth*scale),rh=Math.round(photoImg.naturalHeight*scale),swap=rotation%180!==0;workCanvas.width=swap?rh:rw;workCanvas.height=swap?rw:rh;wctx.save();wctx.translate(workCanvas.width/2,workCanvas.height/2);wctx.rotate(rotation*Math.PI/180);wctx.filter=contrastOn?'contrast(170%) grayscale(100%)':'none';wctx.drawImage(photoImg,-rw/2,-rh/2,rw,rh);wctx.restore();snapData=wctx.getImageData(0,0,workCanvas.width,workCanvas.height).data;snapW=workCanvas.width;snapH=workCanvas.height}
function rgbScore(r,g,b){const min=Math.min(r,g,b),max=Math.max(r,g,b),ink=(255-(r+g+b)/3)+(max-min)*Number($('colorSeparation').value)*.07;if(!training.color)return ink;const [tr,tg,tb]=training.color,dist=Math.hypot(r-tr,g-tg,b-tb),match=Math.max(0,180-dist);return ink+match*.75}
function snapNormPoint(n){if(!snapData)return n;const x=Math.round(n.x*(snapW-1)),y=Math.round(n.y*(snapH-1)),rad=5+Number($('gapTolerance').value);let best={score:-1,x,y};for(let yy=Math.max(0,y-rad);yy<=Math.min(snapH-1,y+rad);yy+=2)for(let xx=Math.max(0,x-rad);xx<=Math.min(snapW-1,x+rad);xx+=2){const i=(yy*snapW+xx)*4,s=rgbScore(snapData[i],snapData[i+1],snapData[i+2])-Math.hypot(xx-x,yy-y)*2;if(s>best.score)best={score:s,x:xx,y:yy}}return{x:best.x/(snapW-1),y:best.y/(snapH-1)}}
function simplify(points,tol=.004){if(points.length<3)return points;const sq=t=>t*t;function rec(a,b,out){let md=0,idx=-1;for(let i=a+1;i<b;i++){const d=distPointSegment(points[i],points[a],points[b]);if(d>md){md=d;idx=i}}if(md>tol&&idx>0){rec(a,idx,out);out.push(points[idx]);rec(idx,b,out)}}const out=[points[0]];rec(0,points.length-1,out);out.push(points[points.length-1]);return out}
function finishTrace(){if(tracePoints.length<2){tracePoints=[];drawPhoto();return}const snapped=simplify(tracePoints.map(snapNormPoint),.0035),start=snapped[0],end=snapped[snapped.length-1];snapshot();let a=traceStartId?graph.nodes.find(n=>n.id===traceStartId):nearestNodeAt(start,.055),b=nearestNodeAt(end,.055);if(!a)a=makePhotoNode(start,'Départ');if(!b||b.id===a.id)b=makePhotoNode(end,'Nouvelle branche');const edge={id:uid('e'),from:a.id,to:b.id,label:'',type:'influence',sourcePath:snapped,confidence:1,verified:true};graph.links.push(edge);selected={kind:'edge',id:edge.id};tracePoints=[];traceStartId=null;setTool('select');learnFromEdge(edge);setStatus('Branche ajoutée et accrochée au trait. Vous pouvez annuler si nécessaire.','ok');renderAll()}
function learnFromEdge(edge){if(!snapData||!edge?.sourcePath?.length)return;let sr=0,sg=0,sb=0,c=0;for(const p of edge.sourcePath){const x=clamp(Math.round(p.x*(snapW-1)),0,snapW-1),y=clamp(Math.round(p.y*(snapH-1)),0,snapH-1),i=(y*snapW+x)*4,r=snapData[i],g=snapData[i+1],b=snapData[i+2];if((r+g+b)/3<245){sr+=r;sg+=g;sb+=b;c++}}if(!c)return;const col=[sr/c,sg/c,sb/c];if(training.color){const k=Math.min(.45,1/(training.count+1));training.color=training.color.map((v,i)=>v*(1-k)+col[i]*k)}else training.color=col;training.count++}
photoCanvas.addEventListener('pointerdown',async e=>{if(!photoImg.naturalWidth)return;if(e.altKey||e.button===1||e.button===2){photoPointer='pan';photoCanvas.setPointerCapture(e.pointerId);photoCanvas.dataset.panX=e.clientX;photoCanvas.dataset.panY=e.clientY;photoCanvas.style.cursor='grabbing';e.preventDefault();return}const n=photoToNorm(e.clientX,e.clientY);if(!n.inside)return;photoPointer=e.pointerId;photoCanvas.setPointerCapture(e.pointerId);if(activeTool==='trace'){if(!snapData)await ensureSnapCanvas();tracing=true;tracePoints=[{x:n.x,y:n.y}];drawPhoto();return}if(activeTool==='add'){snapshot();const node=makePhotoNode(n);selected={kind:'node',id:node.id};renderAll();setTimeout(()=>$('labelInput').focus(),0);return}if(activeTool==='link'){const node=nearestNodeAt(n,.055);if(node)linkNode(node.id);return}if(activeTool==='cut'){const edge=nearestEdgeAt(n,.035);if(edge){snapshot();graph.links=graph.links.filter(x=>x.id!==edge.id);selected=null;renderAll();setStatus('Relation supprimée.','ok')}return}selectFromPhoto(n)});
photoCanvas.addEventListener('pointermove',e=>{if(!photoImg.naturalWidth)return;if(photoPointer==='pan'){photoCam.x+=e.clientX-Number(photoCanvas.dataset.panX||e.clientX);photoCam.y+=e.clientY-Number(photoCanvas.dataset.panY||e.clientY);photoCanvas.dataset.panX=e.clientX;photoCanvas.dataset.panY=e.clientY;drawPhoto();return}const n=photoToNorm(e.clientX,e.clientY);if(n.inside)drawLoupe(n);if(tracing&&e.pointerId===photoPointer){const last=tracePoints[tracePoints.length-1],p={x:n.x,y:n.y};if(!last||Math.hypot(p.x-last.x,p.y-last.y)>.004){tracePoints.push(p);drawPhoto()}}});photoCanvas.addEventListener('pointerup',e=>{if(tracing&&e.pointerId===photoPointer){tracing=false;finishTrace()}photoPointer=null;photoCanvas.style.cursor='';});photoCanvas.addEventListener('pointerleave',()=>{if(!tracing)$('loupe').classList.remove('on')});
photoCanvas.addEventListener('wheel',e=>{if(!photoImg.naturalWidth)return;e.preventDefault();const b=photoCanvas.getBoundingClientRect();zoomPhotoAt(e.deltaY>0?.86:1.16,e.clientX-b.left,e.clientY-b.top)},{passive:false});
photoCanvas.addEventListener('contextmenu',e=>e.preventDefault());
function updatePhotoMeta(){if(!sourceWidth){$('photoInfo').textContent='aucune image';return}$('photoInfo').textContent=`${sourceWidth}×${sourceHeight} · ${sourceMP.toFixed(1)} MP`}
function updateResolutionInfo(w=0,h=0){let t=sourceWidth?`Source : ${sourceWidth}×${sourceHeight} · ${sourceMP.toFixed(1)} MP`:'La prévisualisation est légère ; l’analyse repart de la photo originale.';if(w&&h)t+=` · analyse : ${w}×${h} · ${(w*h/1e6).toFixed(1)} MP`;$('resolutionInfo').textContent=t}
function loadImageSource(src,label='Image chargée'){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{imageDataUrl=src;photoImg=img;sourceWidth=img.naturalWidth;sourceHeight=img.naturalHeight;sourceMP=sourceWidth*sourceHeight/1e6;rotation=0;contrastOn=false;snapData=null;photoCam={z:1,x:0,y:0};updatePhotoMeta();updateResolutionInfo();makePreview();resizePhotoCanvas();setStatus(`${label} : ${sourceWidth}×${sourceHeight} (${sourceMP.toFixed(1)} MP).`,'ok');resolve()};img.onerror=reject;img.src=src})}
function loadFile(file){const url=URL.createObjectURL(file);loadImageSource(url,`Fichier ${file.name||''}`.trim()).then(()=>{try{const rd=new FileReader();rd.onload=()=>{imageDataUrl=rd.result};rd.readAsDataURL(file)}catch{}}).catch(()=>loadImageSource(URL.createObjectURL(file)))}
function makePreview(){if(!photoImg.naturalWidth){$('preview').removeAttribute('src');$('emptyPreview').style.display='flex';drawPhoto();return}const max=1200,s=Math.min(1,max/Math.max(sourceWidth,sourceHeight)),rw=Math.round(sourceWidth*s),rh=Math.round(sourceHeight*s),swap=rotation%180!==0,c=document.createElement('canvas'),x=c.getContext('2d');c.width=swap?rh:rw;c.height=swap?rw:rh;x.save();x.translate(c.width/2,c.height/2);x.rotate(rotation*Math.PI/180);x.filter=contrastOn?'contrast(170%) grayscale(100%)':'none';x.drawImage(photoImg,-rw/2,-rh/2,rw,rh);x.restore();$('preview').src=c.toDataURL('image/jpeg',.92);$('emptyPreview').style.display='none';drawPhoto()}
function chosenMaxDimension(mode='organic'){const q=$('analysisQuality').value;const caps={balanced:4200,high:6400,ultra:8192,native:16384,auto:8192};let max=caps[q]||8192;if(mode==='boxed'&&q!=='native')max=Math.min(max,8192);const src=Math.max(sourceWidth,sourceHeight)||max;return q==='native'?src:Math.min(max,src)}
async function prepareAnalysisCanvas(mode='organic'){if(!photoImg.naturalWidth)throw Error('Aucune image');const max=chosenMaxDimension(mode),s=Math.min(1,max/Math.max(sourceWidth,sourceHeight)),rw=Math.round(sourceWidth*s),rh=Math.round(sourceHeight*s),swap=rotation%180!==0;workCanvas.width=swap?rh:rw;workCanvas.height=swap?rw:rh;wctx.save();wctx.translate(workCanvas.width/2,workCanvas.height/2);wctx.rotate(rotation*Math.PI/180);wctx.filter=contrastOn?'contrast(170%) grayscale(100%)':'none';wctx.drawImage(photoImg,-rw/2,-rh/2,rw,rh);wctx.restore();lastAnalysis={w:workCanvas.width,h:workCanvas.height};updateResolutionInfo(workCanvas.width,workCanvas.height);snapData=null;return{w:workCanvas.width,h:workCanvas.height}}
function otsu(gray){const hist=new Uint32Array(256);for(const v of gray)hist[v]++;let total=gray.length,sum=0;for(let i=0;i<256;i++)sum+=i*hist[i];let sumB=0,wB=0,max=0,thr=127;for(let t=0;t<256;t++){wB+=hist[t];if(!wB)continue;const wF=total-wB;if(!wF)break;sumB+=t*hist[t];const mB=sumB/wB,mF=(sum-sumB)/wF,b=wB*wF*(mB-mF)*(mB-mF);if(b>max){max=b;thr=t}}return thr}
function blurGray(src,w,h){const out=new Uint8Array(src.length),tmp=new Float32Array(src.length),k=[1,2,1];for(let y=0;y<h;y++)for(let x=0;x<w;x++){let s=0,ww=0;for(let i=-1;i<=1;i++){const xx=clamp(x+i,0,w-1),q=k[i+1];s+=src[y*w+xx]*q;ww+=q}tmp[y*w+x]=s/ww}for(let y=0;y<h;y++)for(let x=0;x<w;x++){let s=0,ww=0;for(let i=-1;i<=1;i++){const yy=clamp(y+i,0,h-1),q=k[i+1];s+=tmp[yy*w+x]*q;ww+=q}out[y*w+x]=s/ww}return out}
function integral(src,w,h){const I=new Float64Array((w+1)*(h+1));for(let y=1;y<=h;y++){let row=0;for(let x=1;x<=w;x++){row+=src[(y-1)*w+x-1];I[y*(w+1)+x]=I[(y-1)*(w+1)+x]+row}}return I}
function rectMean(I,w,x0,y0,x1,y1){x0=clamp(x0,0,w);x1=clamp(x1,0,w);y0=clamp(y0,0,(I.length/(w+1))-1);y1=clamp(y1,0,(I.length/(w+1))-1);const W=w+1;return(I[y1*W+x1]-I[y0*W+x1]-I[y1*W+x0]+I[y0*W+x0])/Math.max(1,(x1-x0)*(y1-y0))}
function adaptiveInk(gray,w,h,sens){const I=integral(gray,w,h),dark=new Uint8Array(w*h),r=Math.max(8,Math.round(Math.min(w,h)/(58+Number($('thinBranches').value)*2))),bias=7+(sens-5)*2;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const m=rectMean(I,w,x-r,y-r,x+r+1,y+r+1);dark[y*w+x]=gray[y*w+x]<m-bias?1:0}return dark}
function morph(src,w,h,mode,passes=1){let a=new Uint8Array(src);for(let p=0;p<passes;p++){const b=new Uint8Array(a.length);for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){let c=0;for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++)c+=a[(y+yy)*w+x+xx];b[y*w+x]=mode==='dilate'?(c>0?1:0):(c>=7?1:0)}a=b}return a}
function closeInk(src,w,h){const passes=Number($('gapTolerance').value)>=8?2:1;return morph(morph(src,w,h,'dilate',passes),w,h,'erode',passes)}
function componentBoxes(mask,w,h,minCount,maxCount){const seen=new Uint8Array(mask.length),q=new Int32Array(mask.length),out=[];for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const st=y*w+x;if(!mask[st]||seen[st])continue;let qs=0,qe=0;q[qe++]=st;seen[st]=1;let minX=x,maxX=x,minY=y,maxY=y,count=0;while(qs<qe){const i=q[qs++],xx=i%w,yy=(i/w)|0;count++;minX=Math.min(minX,xx);maxX=Math.max(maxX,xx);minY=Math.min(minY,yy);maxY=Math.max(maxY,yy);for(const k of [i-1,i+1,i-w,i+w])if(k>=0&&k<mask.length&&mask[k]&&!seen[k]){seen[k]=1;q[qe++]=k}}if(count>=minCount&&count<=maxCount)out.push({minX,maxX,minY,maxY,count})}return out}
function iou(a,b){const x0=Math.max(a.minX,b.minX),y0=Math.max(a.minY,b.minY),x1=Math.min(a.maxX,b.maxX),y1=Math.min(a.maxY,b.maxY);if(x1<x0||y1<y0)return 0;const inter=(x1-x0+1)*(y1-y0+1),aa=(a.maxX-a.minX+1)*(a.maxY-a.minY+1),bb=(b.maxX-b.minX+1)*(b.maxY-b.minY+1);return inter/(aa+bb-inter)}
function detectClosedRegions(){const w=workCanvas.width,h=workCanvas.height,im=wctx.getImageData(0,0,w,h).data,raw=new Uint8Array(w*h);for(let p=0,i=0;p<raw.length;p++,i+=4)raw[p]=(im[i]*.299+im[i+1]*.587+im[i+2]*.114)|0;const gray=blurGray(raw,w,h),sens=Number($('sensitivity').value),global=otsu(gray);let dark=adaptiveInk(gray,w,h,sens);for(let i=0;i<dark.length;i++)if(gray[i]<global-18)dark[i]=1;const ink=closeInk(dark,w,h),outside=new Uint8Array(w*h),q=new Int32Array(w*h);let qs=0,qe=0;const push=i=>{if(i>=0&&i<w*h&&!ink[i]&&!outside[i]){outside[i]=1;q[qe++]=i}};for(let x=0;x<w;x++){push(x);push((h-1)*w+x)}for(let y=0;y<h;y++){push(y*w);push(y*w+w-1)}while(qs<qe){const i=q[qs++],x=i%w,y=(i/w)|0;if(x>0)push(i-1);if(x<w-1)push(i+1);if(y>0)push(i-w);if(y<h-1)push(i+w)}const enclosed=new Uint8Array(w*h);for(let i=0;i<enclosed.length;i++)enclosed[i]=(!ink[i]&&!outside[i])?1:0;const comps=componentBoxes(enclosed,w,h,Math.max(90,w*h*.00005),w*h*.22),regions=[];for(const c of comps){const bw=c.maxX-c.minX+1,bh=c.maxY-c.minY+1,area=bw*bh,fill=c.count/area,aspect=bw/bh;if(bw<24||bh<15||area>w*h*.2||aspect>7||aspect<.14||fill<.26)continue;regions.push({...c,cx:(c.minX+c.maxX)/2,cy:(c.minY+c.maxY)/2,score:Math.min(1,.45+fill*.55)})}regions.sort((a,b)=>b.score-a.score);const kept=[];for(const r of regions){if(kept.some(k=>iou(r,k)>.62))continue;kept.push(r)}return{regions:kept.slice(0,60),dark:ink,w,h}}
// Filled circles and outlined bubbles are objects; thin strokes are relationships.
// This detector is deliberately separate from the free-form network detector.
function detectBubbleGraph(){
  const {regions:closed,w,h}=detectClosedRegions(),min=Math.min(w,h),pixels=wctx.getImageData(0,0,w,h).data;
  const filled=new Uint8Array(w*h);
  for(let p=0,i=0;p<filled.length;p++,i+=4){
    const r=pixels[i],g=pixels[i+1],b=pixels[i+2],[,sat,val]=rgbToHSV(r,g,b),gray=.299*r+.587*g+.114*b;
    filled[p]=(sat>.34&&val>.28&&val<.94)||(sat<.16&&gray>105&&gray<205)?1:0;
  }
  let cores=filled;
  const erosion=Math.max(5,Math.round(min/240));
  for(let k=0;k<erosion;k++)cores=morph(cores,w,h,'erode');
  for(let k=0;k<erosion+4;k++)cores=morph(cores,w,h,'dilate');
  const minDiameter=Math.max(32,min*.042),shapes=[];
  for(const c of componentBoxes(cores,w,h,Math.max(250,minDiameter*minDiameter*.13),w*h*.2)){
    const bw=c.maxX-c.minX+1,bh=c.maxY-c.minY+1,ratio=bw/bh;
    if(Math.min(bw,bh)<minDiameter||ratio<.62||ratio>1.6||c.count/(bw*bh)<.42)continue;
    shapes.push({...c,cx:(c.minX+c.maxX)/2,cy:(c.minY+c.maxY)/2,radius:Math.max(bw,bh)/2+6,kind:'filled'});
  }
  for(const c of closed){
    const bw=c.maxX-c.minX+1,bh=c.maxY-c.minY+1,ratio=bw/bh;
    if(Math.min(bw,bh)<minDiameter||ratio<.68||ratio>1.45||c.count/(bw*bh)<.58)continue;
    const shape={...c,radius:Math.max(bw,bh)/2+5,kind:'outlined'};
    if(shapes.every(s=>Math.hypot(s.cx-c.cx,s.cy-c.cy)>Math.max(s.radius,shape.radius)*.65))shapes.push(shape);
  }
  if(shapes.filter(s=>s.kind==='filled').length<2||shapes.length<6)return null;
  const ink=organicInk().ink,links=[],norm=s=>({x:s.cx/w,y:s.cy/h});
  for(let i=0;i<shapes.length;i++)for(let j=i+1;j<shapes.length;j++){
    const a=shapes[i],b=shapes[j],dx=b.cx-a.cx,dy=b.cy-a.cy,d=Math.hypot(dx,dy);
    if(d<Math.max(a.radius,b.radius)*1.4||d>min*.42)continue;
    const ux=dx/d,uy=dy/d,start=a.radius*.98,end=d-b.radius*.98,length=end-start;
    if(length<12)continue;
    const count=Math.max(12,Math.ceil(length/3)),gapLimit=Math.max(4,Math.ceil(count*.16)),offsetMax=clamp(70-length*.13,18,55);
    let hits=0,gap=0,longestGap=0,blocked=false;
    for(let k=0;k<=count;k++){
      const dist=start+length*k/count,x=a.cx+ux*dist,y=a.cy+uy*dist;
      if(shapes.some((s,n)=>n!==i&&n!==j&&Math.hypot(x-s.cx,y-s.cy)<s.radius*.9)){blocked=true;break}
      let hit=false;
      for(let offset=-offsetMax;offset<=offsetMax;offset+=4){const xx=Math.round(x-uy*offset),yy=Math.round(y+ux*offset);if(xx>=0&&yy>=0&&xx<w&&yy<h&&ink[yy*w+xx]){hit=true;break}}
      if(hit){hits++;gap=0}else longestGap=Math.max(longestGap,++gap);
    }
    const coverage=hits/(count+1);
    if(!blocked&&coverage>.72&&longestGap<=gapLimit)links.push({i,j,score:coverage});
  }
  const connected=new Set(links.flatMap(l=>[l.i,l.j]));
  const chosen=shapes.map((shape,i)=>({shape,i})).filter(x=>connected.has(x.i));
  if(chosen.length<6||links.length<5)return null;
  const nodes=chosen.map(({shape,i})=>{const source=norm(shape),p=photoMapPosition(source);return{id:uid('n'),label:shape.kind==='filled'?'Sujet / branche':'Idée',x:p.x,y:p.y,type:'concept',crop:cropAt(shape.cx,shape.cy,shape.radius*2.3,shape.radius*2.3),confidence:Math.round(Math.min(98,65+shape.radius/min*120)),source,_index:i}});
  const byIndex=new Map(nodes.map(n=>[n._index,n]));
  for(const n of nodes)delete n._index;
  const edges=links.filter(l=>byIndex.has(l.i)&&byIndex.has(l.j)).map(l=>{const a=byIndex.get(l.i),b=byIndex.get(l.j);return{id:uid('e'),from:a.id,to:b.id,label:'',type:'influence',confidence:+l.score.toFixed(2),sourcePath:[a.source,b.source]}});
  return{nodes,links:edges};
}
function pointInsideBox(x,y,r,pad=0){return x>=r.minX-pad&&x<=r.maxX+pad&&y>=r.minY-pad&&y<=r.maxY+pad}
function connectionScore(a,b,ink,w,h,regions){const dx=b.cx-a.cx,dy=b.cy-a.cy,d=Math.hypot(dx,dy);if(d<30)return 0;const ux=dx/d,uy=dy/d,px=-uy,py=ux,steps=Math.max(30,Math.round(d/2.5));let hits=0,longest=0,run=0,samples=0;for(let s=0;s<=steps;s++){const t=s/steps;if(t<.12||t>.88)continue;const bx=a.cx+dx*t,by=a.cy+dy*t;let hit=0;for(let rr=-2;rr<=2;rr++){const x=Math.round(bx+px*rr),y=Math.round(by+py*rr);if(x<0||x>=w||y<0||y>=h)continue;let blocked=false;for(const r of regions){if(r===a||r===b)continue;if(pointInsideBox(x,y,r,3)){blocked=true;break}}if(!blocked&&ink[y*w+x]){hit=1;break}}samples++;if(hit){hits++;run++;longest=Math.max(longest,run)}else run=Math.max(0,run-2)}return samples?hits/samples*.48+longest/samples*.62:0}
function rgbToHSV(r,g,b){r/=255;g/=255;b/=255;const mx=Math.max(r,g,b),mn=Math.min(r,g,b),d=mx-mn;let h=0;if(d){if(mx===r)h=((g-b)/d)%6;else if(mx===g)h=(b-r)/d+2;else h=(r-g)/d+4;h*=60;if(h<0)h+=360}return[h,mx?d/mx:0,mx]}
function organicInk(){const w=workCanvas.width,h=workCanvas.height,im=wctx.getImageData(0,0,w,h).data,m=new Uint8Array(w*h),csep=Number($('colorSeparation').value);for(let p=0,i=0;p<m.length;p++,i+=4){const r=im[i],g=im[i+1],b=im[i+2],[,ss,vv]=rgbToHSV(r,g,b),gray=.299*r+.587*g+.114*b;m[p]=((ss>(.18-csep*.008)&&vv<.992)||(gray<165+Number($('thinBranches').value)*2))?1:0}return{ink:closeInk(m,w,h),w,h}}
function boundaryRadius(cx,cy,a,w,h){const ca=Math.cos(a),sa=Math.sin(a),v=[];if(ca>1e-5)v.push((w-1-cx)/ca);else if(ca<-1e-5)v.push((0-cx)/ca);if(sa>1e-5)v.push((h-1-cy)/sa);else if(sa<-1e-5)v.push((0-cy)/sa);return Math.max(1,Math.min(...v.filter(x=>x>0)))}
function rayProfile(ink,w,h,cx,cy,nAngles=360,stepsOverride=0){const scores=new Float32Array(nAngles),r0=Math.max(12,Math.min(w,h)*.035),tube=Math.max(2,Math.min(14,Math.round(Math.min(w,h)/(470-Number($('thinBranches').value)*8)))),steps=stepsOverride||Math.max(120,Math.min(420,Math.round(Math.min(w,h)/8)));for(let k=0;k<nAngles;k++){const a=2*Math.PI*k/nAngles,ca=Math.cos(a),sa=Math.sin(a),px=-sa,py=ca,rmax=boundaryRadius(cx,cy,a,w,h)*.94;let hits=0,longest=0,run=0,weighted=0;for(let q=0;q<steps;q++){const r=r0+(rmax-r0)*q/(steps-1),bx=cx+ca*r,by=cy+sa*r;let hit=0;for(let o=-tube;o<=tube;o++){const x=Math.round(bx+px*o),y=Math.round(by+py*o);if(x>=0&&x<w&&y>=0&&y<h&&ink[y*w+x]){hit=1;break}}hits+=hit;if(hit){run++;longest=Math.max(longest,run);weighted+=.7+.3*q/steps}else run=Math.max(0,run-(Number($('gapTolerance').value)>=6?1:2))}scores[k]=.42*hits/steps+.43*longest/steps+.15*weighted/steps}return scores}
function smoothCircular(a,r=3){const n=a.length,o=new Float32Array(n);for(let i=0;i<n;i++){let s=0,c=0;for(let d=-r;d<=r;d++){s+=a[(i+d+n)%n];c++}o[i]=s/c}return o}
function angleDistance(a,b,n){const d=Math.abs(a-b);return Math.min(d,n-d)}
function chooseRayPeaks(profile,minSepDeg=24,minScore=.16,maxPeaks=8){const s=smoothCircular(profile,3),n=s.length,c=[];for(let i=0;i<n;i++)if(s[i]>=s[(i+n-1)%n]&&s[i]>=s[(i+1)%n]&&s[i]>=minScore)c.push({i,score:s[i]});c.sort((a,b)=>b.score-a.score);const out=[],sep=minSepDeg/360*n;for(const p of c){if(out.every(q=>angleDistance(p.i,q.i,n)>=sep))out.push(p);if(out.length>=maxPeaks)break}return out}
function hubQuality(ink,w,h,cx,cy){const p=rayProfile(ink,w,h,cx,cy,180,105),peaks=chooseRayPeaks(p,24,.1,10);return peaks.slice(0,8).reduce((s,x)=>s+x.score,0)+.13*peaks.length}
function findOrganicHub(ink,w,h){let best={q:-1,cx:w/2,cy:h/2};for(let gy=0;gy<11;gy++)for(let gx=0;gx<13;gx++){const cx=w*(.06+gx*.88/12),cy=h*(.06+gy*.88/10),q=hubQuality(ink,w,h,cx,cy);if(q>best.q)best={q,cx,cy}}let sx=w*.05,sy=h*.05;for(let pass=0;pass<2;pass++){let local=best;for(let yy=-2;yy<=2;yy++)for(let xx=-2;xx<=2;xx++){const cx=clamp(best.cx+xx*sx,0,w-1),cy=clamp(best.cy+yy*sy,0,h-1),q=hubQuality(ink,w,h,cx,cy);if(q>local.q)local={q,cx,cy}}best=local;sx*=.35;sy*=.35}return best}
function cropAt(cx,cy,rw,rh){const x=Math.max(0,Math.round(cx-rw/2)),y=Math.max(0,Math.round(cy-rh/2)),w=Math.max(1,Math.min(workCanvas.width-x,Math.round(rw))),h=Math.max(1,Math.min(workCanvas.height-y,Math.round(rh))),c=document.createElement('canvas');c.width=Math.min(500,w);c.height=Math.min(240,h);c.getContext('2d').drawImage(workCanvas,x,y,w,h,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.88)}
function organicSubPeaks(profile,main,nAngles){const s=smoothCircular(profile,3),range=Math.round(nAngles*31/360),cand=[];for(let d=-range;d<=range;d++){const i=(main.i+d+nAngles)%nAngles;if(s[i]>.1&&s[i]>=s[(i+nAngles-1)%nAngles]&&s[i]>=s[(i+1)%nAngles])cand.push({i,score:s[i]})}cand.sort((a,b)=>b.score-a.score);const out=[],sep=nAngles*4.5/360;for(const p of cand){if(angleDistance(p.i,main.i,nAngles)<nAngles*3/360)continue;if(out.every(q=>angleDistance(p.i,q.i,nAngles)>sep))out.push(p);if(out.length>=6)break}return out}
function detectOrganicMindMap(){const {ink,w,h}=organicInk(),hub=findOrganicHub(ink,w,h),q=$('analysisQuality').value,nAngles=q==='ultra'?1080:q==='balanced'?360:720,profile=rayProfile(ink,w,h,hub.cx,hub.cy,nAngles),sens=Number($('sensitivity').value),threshold=.17-(sens-5)*.009,majors=chooseRayPeaks(profile,18,Math.max(.08,threshold),12);return{ink,w,h,hub,profile,majors,nAngles}}
function rayInkEnd(ink,w,h,cx,cy,a){const ca=Math.cos(a),sa=Math.sin(a),rmax=boundaryRadius(cx,cy,a,w,h)*.97,gap=Math.max(4,Number($('gapTolerance').value)*2);let last=Math.max(28,Math.min(w,h)*.08),miss=0;for(let r=last;r<=rmax;r+=2){const x=Math.round(cx+ca*r),y=Math.round(cy+sa*r);if(x<0||y<0||x>=w||y>=h)break;if(ink[y*w+x]){last=r;miss=0}else if(++miss>gap&&r>last+18)break}return last}
function buildOrganicGraph(det){const {ink,w,h,hub,profile,majors,nAngles}=det,nodes=[],links=[];const norm=(x,y)=>({x:x/w,y:y/h}),map=(n)=>photoMapPosition(n),rootN=norm(hub.cx,hub.cy),rp=map(rootN),root={id:uid('n'),label:'Sujet central',x:rp.x,y:rp.y,type:'concept',crop:cropAt(hub.cx,hub.cy,Math.min(w,h)*.28,Math.min(w,h)*.2),confidence:95,source:rootN};nodes.push(root);majors.sort((a,b)=>a.i-b.i);majors.forEach((p,idx)=>{const a=2*Math.PI*p.i/nAngles,r=Math.max(48,rayInkEnd(ink,w,h,hub.cx,hub.cy,a)*.72),cx=hub.cx+Math.cos(a)*r,cy=hub.cy+Math.sin(a)*r,bn=norm(cx,cy),bp=map(bn),b={id:uid('n'),label:`Branche ${idx+1}`,x:bp.x,y:bp.y,type:'concept',crop:cropAt(cx,cy,Math.min(w*.25,180),Math.min(h*.2,90)),confidence:Math.round(p.score*100),source:bn};nodes.push(b);links.push({id:uid('e'),from:root.id,to:b.id,label:'',type:'influence',confidence:+p.score.toFixed(2),sourcePath:[rootN,bn]});for(const [j,sp] of organicSubPeaks(profile,p,nAngles).entries()){const aa=2*Math.PI*sp.i/nAngles,rr=Math.max(r+24,rayInkEnd(ink,w,h,hub.cx,hub.cy,aa)*.92),scx=hub.cx+Math.cos(aa)*rr,scy=hub.cy+Math.sin(aa)*rr,snN=norm(scx,scy),smp=map(snN),sn={id:uid('n'),label:`Sous-branche ${idx+1}.${j+1}`,x:smp.x,y:smp.y,type:'concept',crop:cropAt(scx,scy,Math.min(w*.22,165),Math.min(h*.17,78)),confidence:Math.round(sp.score*100),source:snN};nodes.push(sn);links.push({id:uid('e'),from:b.id,to:sn.id,label:'',type:'influence',confidence:+sp.score.toFixed(2),sourcePath:[bn,snN]})}});return{nodes,links}}
function detectNetworkGraph(){const {ink,w,h}=organicInk(),step=Math.max(6,Math.round(Math.min(w,h)/95)),minDist=Math.max(18,Math.min(w,h)*.036),cands=[];for(let y=step;y<h-step;y+=step)for(let x=step;x<w-step;x+=step){if(!ink[y*w+x])continue;let c=0,arms=0;for(let k=-4;k<=4;k++){if(ink[y*w+clamp(x+k,0,w-1)])c++;if(ink[clamp(y+k,0,h-1)*w+x])c++}for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1],[1,-1],[-1,-1]]){let hit=0;for(let t=2;t<=step+2;t++){const xx=x+dx*t,yy=y+dy*t;if(xx<0||yy<0||xx>=w||yy>=h)break;if(ink[yy*w+xx])hit++}if(hit>=3)arms++}if(c>=7&&arms>=3)cands.push({x,y,c:c+arms*3})}cands.sort((a,b)=>b.c-a.c);const kept=[];for(const p of cands){if(kept.every(k=>Math.hypot(k.x-p.x,k.y-p.y)>=minDist))kept.push(p);if(kept.length>=90)break}if(kept.length<3)return null;const norm=(x,y)=>({x:x/w,y:y/h}),nodes=kept.map((p,i)=>{const s=norm(p.x,p.y),mp=photoMapPosition(s);return{id:uid('n'),label:`Carrefour ${i+1}`,x:mp.x,y:mp.y,type:'concept',crop:cropAt(p.x,p.y,72,72),confidence:Math.min(99,50+p.c),source:s}});const links=[],maxD=Math.min(w,h)*.2;for(let i=0;i<kept.length;i++)for(let j=i+1;j<kept.length;j++){const dx=kept[j].x-kept[i].x,dy=kept[j].y-kept[i].y,d=Math.hypot(dx,dy);if(d<minDist*1.1||d>maxD)continue;const steps=Math.max(8,Math.round(d/3));let hits=0;for(let s=1;s<steps;s++){const x=Math.round(kept[i].x+dx*s/steps),y=Math.round(kept[i].y+dy*s/steps);if(x>=0&&y>=0&&x<w&&y<h&&ink[y*w+x])hits++}if(hits/steps>.42)links.push({id:uid('e'),from:nodes[i].id,to:nodes[j].id,label:'',type:'flow',confidence:+(hits/steps).toFixed(2),sourcePath:[nodes[i].source,nodes[j].source]})}if(!links.length)return null;return{nodes,links}}
function analyzeBoxed(){const {regions,dark,w,h}=detectClosedRegions();if(!regions.length)return null;const norm=(x,y)=>({x:x/w,y:y/h}),nodes=regions.map((r,i)=>{const s=norm(r.cx,r.cy),p=photoMapPosition(s);return{id:uid('n'),label:`Nœud ${i+1}`,x:p.x,y:p.y,type:'concept',crop:cropAt(r.cx,r.cy,r.maxX-r.minX+30,r.maxY-r.minY+30),confidence:Math.round(r.score*100),source:s}}),cand=[];for(let i=0;i<regions.length;i++)for(let j=i+1;j<regions.length;j++){const d=Math.hypot(regions[i].cx-regions[j].cx,regions[i].cy-regions[j].cy);if(d>Math.max(w,h)*.62)continue;const score=connectionScore(regions[i],regions[j],dark,w,h,regions);if(score>.23)cand.push({i,j,score})}cand.sort((a,b)=>b.score-a.score);const links=cand.slice(0,Math.max(80,nodes.length*4)).map(c=>({id:uid('e'),from:nodes[c.i].id,to:nodes[c.j].id,label:'',type:'influence',confidence:+c.score.toFixed(2),sourcePath:[nodes[c.i].source,nodes[c.j].source]}));return{nodes,links}}
async function analyzeLocal(){if(!photoImg.naturalWidth){setStatus('Ajoutez d’abord une photo.','warn');return}const mode=$('detectMode').value;setStatus('Analyse locale de la photo originale…');await new Promise(r=>setTimeout(r,20));try{snapshot();let result=null,used=mode;if(mode==='boxed'){await prepareAnalysisCanvas('boxed');result=detectBubbleGraph()||analyzeBoxed()}else if(mode==='network'){await prepareAnalysisCanvas('organic');result=detectNetworkGraph();used='network'}else if(mode==='organic'){await prepareAnalysisCanvas('organic');result=buildOrganicGraph(detectOrganicMindMap())}else{await prepareAnalysisCanvas('boxed');const bubbles=detectBubbleGraph();if(bubbles){result=bubbles;used='bubble'}else{await prepareAnalysisCanvas('organic');const net=detectNetworkGraph();if(net&&net.nodes.length>=8&&net.nodes.length<80&&net.links.length>=8&&net.links.length<=net.nodes.length*2.5){result=net;used='network'}else{await prepareAnalysisCanvas('organic');const organic=buildOrganicGraph(detectOrganicMindMap());if(organic.links.length>=3){result=organic;used='organic'}else{await prepareAnalysisCanvas('boxed');result=analyzeBoxed();used='boxed'}}}}if(!result?.nodes?.length)throw Error('Aucune structure exploitable détectée');graph=result;selected=null;training={color:null,count:0};await ensureSnapCanvas();renderAll();fitMap();const label=used==='organic'?'mind map organique':used==='network'?'réseau / plan':used==='bubble'?'bulles et liens':'formes fermées';setStatus(`${graph.nodes.length} éléments et ${graph.links.length} relations détectés (${label}). Corrigez directement sur la photo si nécessaire.`,'ok')}catch(err){setStatus(err.message||String(err),'warn')}}
function renderAll(){renderMap();drawPhoto();updateUI()}
function verifySelected(){if(!selected)return;const obj=selected.kind==='node'?graph.nodes.find(n=>n.id===selected.id):graph.links.find(e=>e.id===selected.id);if(!obj)return;snapshot();obj.verified=true;obj.confidence=100;if(selected.kind==='edge')learnFromEdge(obj);setStatus(selected.kind==='edge'&&training.color?'Relation validée : sa couleur aide maintenant l’accrochage des prochains tracés.':'Élément marqué comme correct.','ok');renderAll()}
function rejectSelected(){if(!selected)return;snapshot();if(selected.kind==='node'){graph.links=graph.links.filter(e=>e.from!==selected.id&&e.to!==selected.id);graph.nodes=graph.nodes.filter(n=>n.id!==selected.id)}else graph.links=graph.links.filter(e=>e.id!==selected.id);selected=null;setStatus('Élément supprimé. Annuler reste possible.','ok');renderAll()}
function continueSelected(){if(!selected)return;let id=null;if(selected.kind==='node')id=selected.id;else{const e=graph.links.find(x=>x.id===selected.id);id=e?.to||null}if(id){traceStartId=id;selected={kind:'node',id};setTool('trace');setStatus('Tracez la suite de cette branche sur la photo.');renderAll()}}
function saveLocal(){try{localStorage.setItem('sketch2map_v6',JSON.stringify({graph,imageDataUrl,rotation,contrastOn,sourceWidth,sourceHeight,sourceMP,training}));setStatus('Projet sauvegardé localement.','ok')}catch{setStatus('Sauvegarde impossible : la photo est peut-être trop volumineuse pour le stockage du navigateur. Exportez le JSON.','warn')}}
async function loadLocal(){try{const s=JSON.parse(localStorage.getItem('sketch2map_v6'));if(!s)throw Error();graph=s.graph||{nodes:[],links:[]};training=s.training||{color:null,count:0};if(s.imageDataUrl){await loadImageSource(s.imageDataUrl,'Projet restauré');rotation=s.rotation||0;contrastOn=!!s.contrastOn;makePreview();resizePhotoCanvas()}renderAll();fitMap()}catch{setStatus('Aucune sauvegarde V6 locale trouvée.','warn')}}
function download(name,type,data){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([data],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),800)}
function exportSVG(){const copy=stage.cloneNode(true);copy.setAttribute('xmlns',NS);return new XMLSerializer().serializeToString(copy)}
function exportPNG(){const svg=exportSVG(),url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'})),img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=1800;c.height=Math.round(1800*view.h/view.w);const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.drawImage(img,0,0,c.width,c.height);c.toBlob(b=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='sketch2map-v6.png';a.click()},'image/png');URL.revokeObjectURL(url)};img.src=url}
function exportMM(){if(!graph.nodes.length)return'';const incoming=new Map(graph.nodes.map(n=>[n.id,0]));graph.links.forEach(e=>incoming.set(e.to,(incoming.get(e.to)||0)+1));const root=graph.nodes.find(n=>incoming.get(n.id)===0)||graph.nodes[0],seen=new Set(),esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));function rec(n){if(seen.has(n.id))return`<node TEXT="${esc(n.label)} (référence)"/>`;seen.add(n.id);const ch=graph.links.filter(e=>e.from===n.id).map(e=>graph.nodes.find(x=>x.id===e.to)).filter(Boolean);return`<node TEXT="${esc(n.label)}">${ch.map(rec).join('')}</node>`}return`<?xml version="1.0" encoding="UTF-8"?><map version="1.0.1">${rec(root)}</map>`}
function doExport(){const t=$('exportSelect').value;if(t==='json')download('sketch2map-v6.json','application/json',JSON.stringify({version:6,graph,training,source:{width:sourceWidth,height:sourceHeight,rotation}},null,2));else if(t==='svg')download('sketch2map-v6.svg','image/svg+xml',exportSVG());else if(t==='png')exportPNG();else download('sketch2map-v6.mm','application/xml',exportMM())}
function setMobilePane(which){$('photoPane').classList.toggle('mobileOn',which==='photo');$('mapPane').classList.toggle('mobileOn',which==='map');$('tabPhoto').classList.toggle('active',which==='photo');$('tabMap').classList.toggle('active',which==='map');if(which==='photo')setTimeout(resizePhotoCanvas,20);else setTimeout(fitMap,20)}
for(const id of ['sensitivity','thinBranches','gapTolerance','colorSeparation']){$(id).addEventListener('input',()=>{$(id+'Val').textContent=$(id).value;if(id==='gapTolerance'&&snapData)setStatus('Tolérance modifiée : elle sera utilisée au prochain tracé.');})}
document.querySelectorAll('.toolBtn').forEach(b=>b.addEventListener('click',()=>setTool(b.dataset.tool)));
$('file').addEventListener('change',e=>e.target.files[0]&&loadFile(e.target.files[0]));$('exampleBtn').onclick=async()=>{try{await loadImageSource('examples/mind-map-organique.jpg','Exemple chargé');$('detectMode').value='organic';await analyzeLocal()}catch{setStatus('L’exemple intégré doit être ouvert via un petit serveur local/PWA. Vous pouvez sélectionner votre propre photo.','warn')}};$('rotateBtn').onclick=()=>{rotation=(rotation+90)%360;snapData=null;makePreview();resizePhotoCanvas();renderAll()};$('contrastBtn').onclick=()=>{contrastOn=!contrastOn;$('contrastBtn').classList.toggle('active',contrastOn);snapData=null;makePreview();renderAll()};$('clearImageBtn').onclick=()=>{imageDataUrl='';photoImg=new Image();sourceWidth=sourceHeight=sourceMP=0;graph={nodes:[],links:[]};selected=null;snapData=null;$('preview').removeAttribute('src');$('emptyPreview').style.display='flex';updatePhotoMeta();updateResolutionInfo();renderAll()};$('analyzeBtn').onclick=analyzeLocal;$('undoBtn').onclick=undo;$('redoBtn').onclick=redo;$('layoutBtn').onclick=autoLayout;$('fitBtn').onclick=fitMap;$('saveBtn').onclick=saveLocal;$('loadBtn').onclick=loadLocal;$('exportBtn').onclick=doExport;$('verifyBtn').onclick=verifySelected;$('rejectBtn').onclick=rejectSelected;$('continueBtn').onclick=continueSelected;$('reverseEdge').onclick=()=>{const e=graph.links.find(x=>x.id===selected?.id);if(e){snapshot();[e.from,e.to]=[e.to,e.from];if(e.sourcePath)e.sourcePath.reverse();renderAll()}};$('labelInput').addEventListener('input',()=>{const n=graph.nodes.find(x=>x.id===selected?.id);if(n){n.label=$('labelInput').value;renderAll()}});$('nodeType').onchange=()=>{const n=graph.nodes.find(x=>x.id===selected?.id);if(n){snapshot();n.type=$('nodeType').value;renderAll()}};$('edgeLabel').addEventListener('input',()=>{const e=graph.links.find(x=>x.id===selected?.id);if(e){e.label=$('edgeLabel').value;renderAll()}});$('edgeType').onchange=()=>{const e=graph.links.find(x=>x.id===selected?.id);if(e){snapshot();e.type=$('edgeType').value;renderAll()}};$('tabPhoto').onclick=()=>setMobilePane('photo');$('tabMap').onclick=()=>setMobilePane('map');
window.addEventListener('resize',()=>{resizePhotoCanvas();renderMap()});window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}else if(e.key==='Escape'){tracePoints=[];tracing=false;setTool('select');renderAll()}else if((e.key==='Delete'||e.key==='Backspace')&&selected&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();rejectSelected()}});
if('ResizeObserver'in window)new ResizeObserver(resizePhotoCanvas).observe($('photoStage'));resizePhotoCanvas();renderAll();setTool('select');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
